### ISSUE TITLE
Add packages/projects to Ozzie

### ISSUE THREAD

**Issue by jakebathman** [tightenco/ozzie#11]
These need to be added to `projects.json`, with maintainers set:

* onramp
* parental
* version-check
* tightendotco
* jigsaw-blog-template
* omgphp

**Comment by mattstauffer** [comment]
add jigsaw-docs-template
drop tightendotco because right now ozzie is only for open source
add whyphp

**Comment by mattstauffer** [comment]
For anyone who picks this up, this is stored in the code, in `/projects.json`, for now.

**Comment by josecanhelp** [comment]
Is `version-check` supposed to be open source and on `ozzie`? It is set to private right now.
I don't see `whyphp` in our github. Is it not public yet?

**Comment by josecanhelp** [comment]
Work in Progress is on branch `new-projects`. I didn't know where to get the maintainers list.

**Comment by mattstauffer** [comment]
Whoops, `whyphp` is public now.

**Comment by mattstauffer** [comment]
Maintainers for now: 

- onramp: matt
- parental: caleb
- version-check: matt, jake
- jigsaw-blog-template: keith, matt, ant
- omgphp: matt
- whyphp: matt

**Comment by mattstauffer** [comment]
Also, version check could be open source I guess :) will double check but yah i think so
