### ISSUE TITLE
Fix modals to render dependabot PRs correctly

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/ozzie#33]

**Comment by sbine** [comment]
@mattstauffer I *think* this has been fixed, currently the dependabot PRs look pretty similar to other PRs to me. Could you reopen this and provide more info if it's still an issue? 😄

![image](https://user-images.githubusercontent.com/1902973/84534377-06b0fe00-aca7-11ea-8395-706ada0a1231.png)

![image](https://user-images.githubusercontent.com/1902973/84534446-2516f980-aca7-11ea-84cb-b89a4631852d.png)

**Comment by mattstauffer** [comment]
@sbine haha will do if I see it again. Thanks!
