### ISSUE TITLE
Ozzie app and Github timezone mismatch.

### ISSUE THREAD

**Issue by jonsugar** [tightenco/ozzie#46]
A minor issue here in the grand scheme of things that I would normally just PR but I'm wondering if there is a reason why Ozzie uses America/Chicago as its timezone.

## Issue
In `config/app.php` Ozzie's timezone is configured as `'timezone' => 'America/Chicago'` while Github uses UTC. This creates a mismatch in timestamps:

**Ozzie** 
![Screenshot 2020-06-27 at 11 54 16](https://user-images.githubusercontent.com/1974648/86124459-1320bd80-bad3-11ea-91dd-3deec3fa3e09.png)

**Github**
![Screenshot 2020-06-27 at 11 54 48](https://user-images.githubusercontent.com/1974648/86124473-16b44480-bad3-11ea-96fe-d734f8f13cd5.png)

## Fix
There are a couple of one-line fixes that spring to mind:

1. Set Ozzie's timezone as `'timezone' => 'UTC'` in `config/app.php`—this is what [Carbon suggests as best practice](https://carbon.nesbot.com/docs/#api-timezone) and would align the servers.
1. In `app/GitHub/Dto/CastDates.php:14` specify the timezone when creating the Carbon instance—preferable if there is a good reason why Ozzie needs to use  America/Chicago as it's timezone.

```php
// Current
Carbon::createFromFormat('Y-m-d\TG:i:s\Z', $date);

// Fix
Carbon::createFromFormat('Y-m-d\TG:i:s\Z', $date, 'UTC');
```

**Comment by jakebathman** [comment]
Good catch. I can’t think of a reason we’d need to specify Chicago. 

Since all times shows are relative and Ozzie is basically just a filtered GitHub viewer, I’d say let’s specify the timezone as UTC in the config to unify everything.

**Comment by jonsugar** [comment]
Cool. Will make PR.
